openapi: 3.2.0
info:
  version: 1.3.0
  title: CryptoQuant Data BTC Inter Entity Flows API
  termsOfService: https://cryptoquant.com/terms-of-service
  contact:
    name: API Support
    email: contact@cryptoquant.com
  description: The CryptoQuant Data API provides simple and powerful endpoints to get information on general transaction data and aggregate on-chain statistics straight from the blockchain. The API root endpoint URL is `https://api.cryptoquant.com/v1/`.
servers:
- url: https://api.cryptoquant.com/v1
  description: Default server
tags:
- name: BTC Inter Entity Flows
  description: 'This namespace contains endpoints to retrieve inter entity flows data (e.g. flow between miners and exchanges). Data entries were collected from the first transaction between two entities.

    We constantly keep updating new entity wallets, which means that there can be slight modification in values especially for recent data points.

    The update is done in periodic and automatic way: Tuesday 00:00 UTC every week.


    > **Note:** This endpoint does not support Point-In-Time (PIT) accuracy due to periodic updates to wallet address clustering. Historical data may change as new entity wallets are discovered, added, and validated.'
paths:
  /btc/inter-entity-flows/exchange-to-exchange:
    get:
      tags:
      - BTC Inter Entity Flows
      summary: Exchange to Exchange
      description: 'This endpoint contains metrics related to token flows between exchanges. We provide several metrics, `flow_total`, the total number of tokens transferred from one exchange to another, `flow_mean`, the mean of tokens transferred, and `transactions_count_flow`, the number of transactions between exchanges.


        **📖 Data Guide:** Exchange to Exchange — definition, interpretation, and chart examples.'
      operationId: BTCgetExchangeToExchange
      parameters:
      - description: An exchange from the table that we support. [See here](#tag/BTC-Exchange-Flows).
        explode: false
        in: query
        name: from_exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: An exchange from the table that we support. [See here](#tag/BTC-Exchange-Flows). This should not be same as `from_entity`.
        explode: false
        in: query
        name: to_exchange
        required: true
        schema:
          type: string
        style: form
        example: bithumb
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-exchange?from_exchange=binance&to_exchange=bithumb&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-exchange?from_exchange=binance&to_exchange=bithumb&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-exchange?from_exchange=binance&to_exchange=bithumb&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-exchange?from_exchange=binance&to_exchange=bithumb&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-exchange?from_exchange=binance&to_exchange=bithumb&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: from_exchange, to_exchange, flow
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - flow_total
                          - flow_mean
                          - transactions_count_flow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            flow_total:
                              type: number
                              description: The total number of tokens transferred from one exchange to another.
                            flow_mean:
                              type: number
                              description: The mean of tokens transferred from one exchange to another.
                            transactions_count_flow:
                              type: number
                              description: The number of transactions from one exchange to another.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-15'
                    flow_total: 15.024803
                    flow_mean: 0.60099212
                    transactions_count_flow: 25
                  - date: '2026-06-14'
                    flow_total: 48.936306
                    flow_mean: 1.6312102
                    transactions_count_flow: 30
      security:
      - AccessToken: []
  /btc/inter-entity-flows/miner-to-exchange:
    get:
      tags:
      - BTC Inter Entity Flows
      summary: Miner to Exchange
      description: 'This endpoint contains metrics related to token flows from mining pools to exchanges. We provide several metrics, `flow_total`, the total number of tokens transferred from a mining pool to an exchange, `flow_mean`, the mean of tokens transferred, and `transactions_count_flow`, the number of transactions from a mining pool to an exchange.


        **📖 Data Guide:** Miner to Exchange — definition, interpretation, and chart examples.'
      operationId: BTCgetMinerToExchange
      parameters:
      - description: A mining pool from the table that we support. [See here](#tag/BTC-Miner-Flows).
        explode: false
        in: query
        name: from_miner
        required: true
        schema:
          type: string
        style: form
        example: f2pool
      - description: An exchange from the table that we support. [See here](#tag/BTC-Exchange-Flows). This should not be same as `from_entity`.
        explode: false
        in: query
        name: to_exchange
        required: true
        schema:
          type: string
        style: form
        example: bithumb
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-exchange?from_miner=f2pool&to_exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-exchange?from_miner=f2pool&to_exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-exchange?from_miner=f2pool&to_exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-exchange?from_miner=f2pool&to_exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-exchange?from_miner=f2pool&to_exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: from_miner, to_exchange, flow
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - flow_total
                          - flow_mean
                          - transactions_count_flow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            flow_total:
                              type: number
                              description: The total number of tokens transferred from a mining pool to an exchange.
                            flow_mean:
                              type: number
                              description: The mean of tokens transferred from a mining pool to an exchange.
                            transactions_count_flow:
                              type: number
                              description: The number of transactions from a mining pool to an exchange.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    flow_total: 0
                    transactions_count_flow: 0
                    flow_mean: 0
                  - date: '2026-06-13'
                    flow_total: 0
                    transactions_count_flow: 0
                    flow_mean: 0
      security:
      - AccessToken: []
  /btc/inter-entity-flows/exchange-to-miner:
    get:
      tags:
      - BTC Inter Entity Flows
      summary: Exchange to Miner
      description: This endpoint contains metrics related to token flows from exchanges to mining pools. We provide several metrics, `flow_total`, the total number of tokens transferred from a mining pool to an exchange, `flow_mean`, the mean of tokens transferred, and `transactions_count_flow`, the number of transactions from an exchange to a mining pool.
      operationId: BTCgetExchangeToMiner
      parameters:
      - description: An exchange from the table that we support. [See here](#tag/BTC-Exchange-Flows).
        explode: false
        in: query
        name: from_exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: A mining pool from the table that we support. [See here](#tag/BTC-Miner-Flows).
        explode: false
        in: query
        name: to_miner
        required: true
        schema:
          type: string
        style: form
        example: f2pool
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-miner?from_exchange=binance&to_miner=f2pool&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-miner?from_exchange=binance&to_miner=f2pool&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-miner?from_exchange=binance&to_miner=f2pool&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-miner?from_exchange=binance&to_miner=f2pool&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/btc/inter-entity-flows/exchange-to-miner?from_exchange=binance&to_miner=f2pool&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: from_exchange, to_miner, flow
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - flow_total
                          - flow_mean
                          - transactions_count_flow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            flow_total:
                              type: number
                              description: The total number of tokens transferred from an exchange to a mining pool.
                            flow_mean:
                              type: number
                              description: The mean of tokens transferred from an exchange to a mining pool.
                            transactions_count_flow:
                              type: number
                              description: The number of transactions from an exchange to a mining pool.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    flow_total: 0.00188
                    transactions_count_flow: 2
                    flow_mean: 0.00094
                  - date: '2026-06-13'
                    flow_total: 0.14622697
                    transactions_count_flow: 8
                    flow_mean: 0.01827837
      security:
      - AccessToken: []
  /btc/inter-entity-flows/miner-to-miner:
    get:
      tags:
      - BTC Inter Entity Flows
      summary: Miner to Miner
      description: This endpoint contains metrics related to token flows between mining pools. We provide several metrics, `flow_total`, the total number of tokens transferred from one mining pool to another, `flow_mean`, the mean of tokens transferred, and `transactions_count_flow`, the number of transactions between mining pools.
      operationId: BTCgetMinerToMiner
      parameters:
      - description: A mining pool from the table that we support. [See here](#tag/BTC-Miner-Flows).
        explode: false
        in: query
        name: from_miner
        required: true
        schema:
          type: string
        style: form
        example: f2pool
      - description: A mining pool from the table that we support. [See here](#tag/BTC-Miner-Flows).
        explode: false
        in: query
        name: to_miner
        required: true
        schema:
          type: string
        style: form
        example: f2pool
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-miner?from_miner=f2pool&to_miner=antpool&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-miner?from_miner=f2pool&to_miner=antpool&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-miner?from_miner=f2pool&to_miner=antpool&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-miner?from_miner=f2pool&to_miner=antpool&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/btc/inter-entity-flows/miner-to-miner?from_miner=f2pool&to_miner=antpool&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: from_miner, to_miner, flow
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - flow_total
                          - flow_mean
                          - transactions_count_flow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            flow_total:
                              type: number
                              description: The total number of tokens transferred from one mining pool to another.
                            flow_mean:
                              type: number
                              description: The mean of tokens transferred from one mining pool to another.
                            transactions_count_flow:
                              type: number
                              description: The number of transactions from one mining pool to another.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    flow_total: 0.01240324
                    transactions_count_flow: 1
                    flow_mean: 0.01240324
                  - date: '2026-06-13'
                    flow_total: 0.01588166
                    transactions_count_flow: 1
                    flow_mean: 0.01588166
      security:
      - AccessToken: []
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'For each API request, include this HTTP header:

        `Authorization` with the `Bearer <YOUR_API_KEY>`. Bearer access token is the type of HTTP Authorization.  You have to include access token to the HTTP header and note that leading bearer is required.

        You must include your access token in HTTP header in every request you make. The token is unique, issued for each client, and regularly changed(once a year). To obtain an access token, please [upgrade your plan](https://cryptoquant.com/pricing) to Professional or Premium plan. You''ll be able to see your access token on the [API tab](https://cryptoquant.com/settings/api) of your profile page after the subscription.'
    QueryParameter:
      type: apiKey
      name: api_key
      in: query
      description: 'For each API reqeust, include `api_key` parameter.

        You must request with your access token in query parameter in every request you make. The token is unique, issued for each client, and regularly changed(once a year). To obtain an access token, please [upgrade your plan](https://cryptoquant.com/pricing) to Professional or Premium plan. You''ll be able to see your access token on the [API tab](https://cryptoquant.com/settings/api) of your profile page after the subscription.

        If you are using Excel, you can use the `api_key` parameter to request with your access token to return data either in `json` or `csv`.'
x-tagGroups:
- name: Discovery
  tags:
  - Available Endpoints
  - Supported Stablecoin List
  - Supported ERC20 List
  - Supported Alt List
- name: Bitcoin
  tags:
  - BTC Entity Status
  - BTC Exchange Flows
  - BTC Flow Indicator
  - BTC Market Indicator
  - BTC Network Indicator
  - BTC Miner Flows
  - BTC Inter Entity Flows
  - BTC Fund Data
  - BTC Market Data
  - BTC Miner Data
  - BTC Network Data
  - BTC Mempool Statistics
  - BTC Lightning Statistics
- name: Ethereum
  tags:
  - ETH Entity Status
  - ETH Exchange Flows
  - ETH Flow Indicator
  - ETH Market Indicator
  - ETH 2.0
  - ETH Fund Data
  - ETH Market Data
  - ETH Network Data
- name: XRP
  tags:
  - XRP Entity Status
  - XRP Entity Flows
  - XRP Flow Indicator
  - XRP Market Data
  - XRP Network Data
  - XRP Network Indicator
  - XRP Dex Data
  - XRP AMM Data
- name: TRX
  tags:
  - TRX Market Data
  - TRX Network Data
  - TRX DEFI
- name: Stablecoin
  tags:
  - Stablecoin Entity Status
  - Stablecoin Exchange Flows
  - Stablecoin Flow Indicator
  - Stablecoin Market Data
  - Stablecoin Network Data
- name: ERC20
  tags:
  - ERC20 Entity Status
  - ERC20 Exchange Flows
  - ERC20 Flow Indicator
  - ERC20 Market Data
  - ERC20 Network Data
- name: Alt
  tags:
  - Alt Market Data
- name: Utilities
  tags:
  - Latency
