openapi: 3.2.0
info:
  version: 1.3.0
  title: CryptoQuant Data ERC20 Exchange Flows API
  termsOfService: https://cryptoquant.com/terms-of-service
  contact:
    name: API Support
    email: contact@cryptoquant.com
  description: The CryptoQuant Data API provides simple and powerful endpoints to get information on general transaction data and aggregate on-chain statistics straight from the blockchain. The API root endpoint URL is `https://api.cryptoquant.com/v1/`.
servers:
- url: https://api.cryptoquant.com/v1
  description: Default server
tags:
- name: ERC20 Exchange Flows
  description: 'This endpoint returns the flows of ERC20 tokens into exchange wallets for as far back as we track. Please note that the transfer generally occurs after a certain amount of time from the contract created time.

    We constantly keep updating new exchange wallets, which means that there can be slight modification in values especially for recent data points.

    The update is done in periodic and automatic way: Tuesday 00:00 UTC every week.

    Supported exchanges can be found in the `/erc20/status/entity-list` endpoint.

    In addition to that, we support the following aggregated exchanges:


    ### Supported Aggregated Exchanges

    | Name | Exchange | Supported ERC20 Tokens |

    |----------------|----------------|-------------------------------|

    | All Exchanges | `all_exchange` | All Tokens |

    | Spot Exchanges | `spot_exchange` | All Tokens |

    | Derivative Exchanges | `derivative_exchange` | All Tokens |


    > **Note:** This endpoint does not support Point-In-Time (PIT) accuracy due to periodic updates to wallet address clustering. Historical data may change as new exchange wallets are discovered, added, and validated.'
paths:
  /erc20/exchange-flows/reserve:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Reserve
      description: 'This endpoint returns the full historical on-chain ERC20 token balance of exchanges.


        **📖 Data Guide:** Exchange Reserve — definition, interpretation, and chart examples.'
      operationId: ERC20GetReserve
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/reserve?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/reserve?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/reserve?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/reserve?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/reserve?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: The amount of ERC20 token on a given exchange on this window.
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - reserve
                          - reserve_usd
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            reserve:
                              type: number
                              description: The amount of ERC20 token held by an exchange.
                            reserve_usd:
                              type: number
                              description: The USD value of ERC20 token held by an exchange.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    reserve: 84122235.99
                    reserve_usd: 687588701.38
                  - date: '2026-06-13'
                    reserve: 84206801.25
                    reserve_usd: 671535910.84
      security:
      - AccessToken: []
  /erc20/exchange-flows/netflow:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Netflow
      description: 'The difference between coins flowing into exchanges and flowing out of exchanges. Netflow usually helps us to figure out an increase of idle coins waiting to be traded in a certain time frame.


        **📖 Data Guide:** Exchange In/Outflow and Netflow — definition, interpretation, and chart examples.'
      operationId: ERC20GetExchangeNetflow
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/netflow?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/netflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/netflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/netflow?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/netflow?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: netflow_total
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - netflow_total
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            netflow_total:
                              type: number
                              description: The difference between coins flowing into/out of exchanges.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    netflow_total: -84565.26
                  - date: '2026-06-13'
                    netflow_total: -56641.56
      security:
      - AccessToken: []
  /erc20/exchange-flows/inflow:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Inflow
      description: 'This endpoint returns the inflow of ERC20 token into exchange wallets for as far back as we track. The average inflow is the average transaction value for transactions flowing into exchange wallets on a given day.


        **📖 Data Guide:** Exchange In/Outflow and Netflow — definition, interpretation, and chart examples.'
      operationId: ERC20GetInflow
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/inflow?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/inflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/inflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/inflow?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/inflow?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: inflow_total, inflow_top10, inflow_mean
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - inflow_total
                          - inflow_top10
                          - inflow_mean
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            inflow_total:
                              type: number
                              description: The total amount of ERC20 token that transferred to the exchange.
                            inflow_top10:
                              type: number
                              description: The total ERC20 token amount of top 10 transactions (in terms of total tokens sent) flowing out of exchange wallets for every day that the exchange wallets we track have been live on the blockchain.
                            inflow_mean:
                              type: number
                              description: The mean of tokens per transaction sent an exchange.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    inflow_total: 263274.33
                    inflow_top10: 2771.31
                    inflow_mean: 2556.06
                    inflow_mean_ma7: 2582.95
                  - date: '2026-06-13'
                    inflow_total: 302767.98
                    inflow_top10: 3058.26
                    inflow_mean: 2911.23
                    inflow_mean_ma7: 2607.69
      security:
      - AccessToken: []
  /erc20/exchange-flows/outflow:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Outflow
      description: 'This endpoint returns the outflow of ERC20 token into exchange wallets for as far back as we track. The average outflow is the average transaction value for transactions flowing into exchange wallets on a given day.


        **📖 Data Guide:** Exchange In/Outflow and Netflow — definition, interpretation, and chart examples.'
      operationId: ERC20GetOutflow
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/outflow?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/outflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/outflow?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/outflow?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/outflow?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: outflow_total, outflow_top10, outflow_mean
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - outflow_total
                          - outflow_top10
                          - outflow_mean
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            outflow_total:
                              type: number
                              description: The total amount of ERC20 token that transferred from the exchange
                            outflow_top10:
                              type: number
                              description: The total ERC20 token amount of top 10 transactions (in terms of total tokens sent) flowing out of exchange wallets for every day that the exchange wallets we track have been live on the blockchain.
                            outflow_mean:
                              type: number
                              description: The mean of tokens per transaction sent from an exchange.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    outflow_total: 347839.59
                    outflow_top10: 1539.11
                    outflow_mean: 1467.68
                    outflow_mean_ma7: 1721.67
                  - date: '2026-06-13'
                    outflow_total: 359409.54
                    outflow_top10: 1824.41
                    outflow_mean: 1797.05
                    outflow_mean_ma7: 1705.54
      security:
      - AccessToken: []
  /erc20/exchange-flows/transactions-count:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Transactions Count
      description: 'This endpoint returns the number of transactions flowing in/out of ERC20 token exchanges.


        **📖 Data Guide:** Exchange Transactions Count — definition, interpretation, and chart examples.'
      operationId: ERC20GetTransactionsCountEF
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/transactions-count?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/transactions-count?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/transactions-count?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/transactions-count?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/transactions-count?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: transactions_count_inflow, transactions_count_outflow
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - transactions_count_inflow
                          - transactions_count_outflow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            transactions_count_inflow:
                              type: number
                              description: The number of transactions sent to the exchange .
                            transactions_count_outflow:
                              type: number
                              description: The number of transactions sent from the exchange.
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    transactions_count_inflow: 103
                    transactions_count_outflow: 237
                  - date: '2026-06-13'
                    transactions_count_inflow: 104
                    transactions_count_outflow: 200
      security:
      - AccessToken: []
  /erc20/exchange-flows/addresses-count:
    get:
      tags:
      - ERC20 Exchange Flows
      summary: Addresses Count
      description: 'This endpoint returns the number of addresses involved in inflow/outflow transactions.


        **📖 Data Guide:** Exchange Addresses Count — definition, interpretation, and chart examples.'
      operationId: ERC20GetAddressesCountEF
      parameters:
      - description: A ERC20 token from the table that we support. [See here](#tag/Supported-ERC20-List)
        explode: false
        in: query
        name: token
        required: true
        schema:
          type: string
        style: form
        example: link
      - description: An exchange from the table that we support. Please check the supported exchanges for each token from [here](#tag/ERC20-Exchange-Flows).
        explode: false
        in: query
        name: exchange
        required: true
        schema:
          type: string
        style: form
        example: binance
      - description: Currently we support `day`, `hour`, and `block`.
        explode: false
        in: query
        name: window
        schema:
          type: string
          default: day
        style: form
        example: day
      - description: This defines the starting time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the earliest time.
        explode: false
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
        example: 20191001T100000
      - description: This defines the ending time for which data will be gathered, formatted as YYYYMMDDTHHMMSS (indicating YYYY-MM-DDTHH:MM:SS, UTC time). If window=day is used, it can also be formatted as YYYYMMDD (date). If window=block is used, you can also specify the exact block height (e.g. 510000). If this field is not specified, response will include data from the latest time.
        explode: false
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
        example: 20191001T103025
      - description: The maximum number of entries to return before the latest data point (or before `to` if specified). This field ranges from 1 to 100,000.
        explode: false
        in: query
        name: limit
        required: false
        schema:
          type: integer
          default: 100
          minimum: 1
          maximum: 100000
        style: form
        example: 100
      - description: A format type about return message type. Supported formats are json, csv.
        explode: false
        in: query
        name: format
        required: false
        schema:
          type: string
          default: json
        style: form
        example: json
      x-codeSamples:
      - lang: Shell
        source: 'curl -X GET "https://api.cryptoquant.com/v1/erc20/exchange-flows/addresses-count?token=link&exchange=binance&window=day&from=20191001&limit=2" \

          -H "Authorization: Bearer <YOUR_API_KEY>"'
      - lang: JavaScript
        source: "fetch(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/addresses-count?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { \"Authorization\": \"Bearer <YOUR_API_KEY>\"} })\n  .then(response => response.json())\n  .then(data => console.log(data))"
      - lang: NodeJS
        source: "require('axios')\n  .get(\"https://api.cryptoquant.com/v1/erc20/exchange-flows/addresses-count?token=link&exchange=binance&window=day&from=20191001&limit=2\", { headers: { Authorization: 'Bearer <YOUR_API_KEY>' } })\n  .then(response => console.log(response))"
      - lang: Ruby
        source: 'require ''net/http''

          uri = URI("https://api.cryptoquant.com/v1/erc20/exchange-flows/addresses-count?token=link&exchange=binance&window=day&from=20191001&limit=2")

          req = Net::HTTP::Get.new(uri)

          req["Authorization"] = "Bearer <YOUR_API_KEY>"

          res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }

          puts res.body'
      - lang: Python
        source: 'import requests

          headers = {''Authorization'': ''Bearer <YOUR_API_KEY>''}

          url = "https://api.cryptoquant.com/v1/erc20/exchange-flows/addresses-count?token=link&exchange=binance&window=day&from=20191001&limit=2"

          print(requests.get(url, headers=headers).json())'
      responses:
        '200':
          description: The number of addresses evoking inflow/outflow transactions to exchange wallets
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - result
                properties:
                  status:
                    type: object
                    description: The status object is return with most of requests and indicates if the request was successful. If it is not successful, error information is included.
                    properties:
                      code:
                        type: integer
                        format: int32
                        description: HTTP status code
                      message:
                        type: string
                        description: Text description of the error or success.
                    required:
                    - code
                    - message
                  result:
                    type: object
                    required:
                    - window
                    - data
                    properties:
                      window:
                        type: string
                        description: The size of window. It can be day, hour, or block, and it depends on the user request.
                      data:
                        type: array
                        items:
                          type: object
                          required:
                          - addresses_count_inflow
                          - addresses_count_outflow
                          properties:
                            blockheight:
                              type: string
                              description: The height of the block. This optional field only appears when window=block is used.
                            date:
                              type: string
                              description: The date in YYYY-DD-MM. This optional field only appears when window=day is used.
                            datetime:
                              type: string
                              description: The date and time formatted as YYYY-MM-DD HH:MM:SS (UTC time). This field only appears when window=block or window=hour is used.
                            addresses_count_inflow:
                              type: number
                              description: The number of addresses evoking inflow transactions to exchange wallets
                            addresses_count_outflow:
                              type: number
                              description: The number of addresses evoking outflow transactions from exchange wallets
              example:
                status:
                  code: 200
                  message: success
                result:
                  window: day
                  data:
                  - date: '2026-06-14'
                    addresses_count_inflow: 67
                    addresses_count_outflow: 161
                  - date: '2026-06-13'
                    addresses_count_inflow: 67
                    addresses_count_outflow: 153
      security:
      - AccessToken: []
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'For each API request, include this HTTP header:

        `Authorization` with the `Bearer <YOUR_API_KEY>`. Bearer access token is the type of HTTP Authorization.  You have to include access token to the HTTP header and note that leading bearer is required.

        You must include your access token in HTTP header in every request you make. The token is unique, issued for each client, and regularly changed(once a year). To obtain an access token, please [upgrade your plan](https://cryptoquant.com/pricing) to Professional or Premium plan. You''ll be able to see your access token on the [API tab](https://cryptoquant.com/settings/api) of your profile page after the subscription.'
    QueryParameter:
      type: apiKey
      name: api_key
      in: query
      description: 'For each API reqeust, include `api_key` parameter.

        You must request with your access token in query parameter in every request you make. The token is unique, issued for each client, and regularly changed(once a year). To obtain an access token, please [upgrade your plan](https://cryptoquant.com/pricing) to Professional or Premium plan. You''ll be able to see your access token on the [API tab](https://cryptoquant.com/settings/api) of your profile page after the subscription.

        If you are using Excel, you can use the `api_key` parameter to request with your access token to return data either in `json` or `csv`.'
x-tagGroups:
- name: Discovery
  tags:
  - Available Endpoints
  - Supported Stablecoin List
  - Supported ERC20 List
  - Supported Alt List
- name: Bitcoin
  tags:
  - BTC Entity Status
  - BTC Exchange Flows
  - BTC Flow Indicator
  - BTC Market Indicator
  - BTC Network Indicator
  - BTC Miner Flows
  - BTC Inter Entity Flows
  - BTC Fund Data
  - BTC Market Data
  - BTC Miner Data
  - BTC Network Data
  - BTC Mempool Statistics
  - BTC Lightning Statistics
- name: Ethereum
  tags:
  - ETH Entity Status
  - ETH Exchange Flows
  - ETH Flow Indicator
  - ETH Market Indicator
  - ETH 2.0
  - ETH Fund Data
  - ETH Market Data
  - ETH Network Data
- name: XRP
  tags:
  - XRP Entity Status
  - XRP Entity Flows
  - XRP Flow Indicator
  - XRP Market Data
  - XRP Network Data
  - XRP Network Indicator
  - XRP Dex Data
  - XRP AMM Data
- name: TRX
  tags:
  - TRX Market Data
  - TRX Network Data
  - TRX DEFI
- name: Stablecoin
  tags:
  - Stablecoin Entity Status
  - Stablecoin Exchange Flows
  - Stablecoin Flow Indicator
  - Stablecoin Market Data
  - Stablecoin Network Data
- name: ERC20
  tags:
  - ERC20 Entity Status
  - ERC20 Exchange Flows
  - ERC20 Flow Indicator
  - ERC20 Market Data
  - ERC20 Network Data
- name: Alt
  tags:
  - Alt Market Data
- name: Utilities
  tags:
  - Latency
